name: Create release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'milestone|patch|minor'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Validate inputs
        run: exit 1
        if: |
          github.event.inputs.releaseType != 'minor' &&
          github.event.inputs.releaseType != 'patch' &&
          github.event.inputs.releaseType != 'milestone'

      - uses: actions/checkout@v2

      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.ivy2/cache
            ~/.cache/coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/plugins.sbt', '**/build.properties') }}

      - name: Next version
        id: tag
        run: |
          export CURRENT_TAG="v$(sbt -no-colors -Dsbt.supershell=false -error 'print gatlingBumpVersion ${{ github.event.inputs.releaseType }}')"
          git tag "$CURRENT_TAG" -m "Version $CURRENT_TAG"
          git push origin "$CURRENT_TAG"
          echo "::set-output name=tag::$CURRENT_TAG"

    outputs:
      tag: ${{ steps.tag.outputs.tag }}
